version: '3'
services:
  scrapy:
    build: .
    command: "pipenv run scrapy crawl rotten_tomatoes"
    depends_on:
      - mongodb

  app:
    build: .
    command: "pipenv run python run.py"
    ports:
      - "5000:5000"
    depends_on:
      - scrapy

  mongodb:
    image: mongo
    ports:
      - "27017:27017"